title: Levente Bajczi
logo: /assets/img/adamzsofi.jpg
description: Computer scientist, PhD Student
website1: https://ftsrg.mit.bme.hu
affiliation1: Critical Systems Research Group
title1: PhD Student
scholar: 8lSh8hYAAAAJ
mail: adamzsofi@edu.bme.hu
linkedin: zsofiaadam4224
theme: jekyll-theme-minimal
